### ISSUE TITLE
Error in Create Event Page

### ISSUE THREAD

**Issue by Draxxus702** [Lambda-School-Labs/community-calendar-fe#124]
While in the create event page if you click the create event tab again in the nav bar you get a "TypeError: Cannot read property 'contains' of null"

![BROKEN](https://user-images.githubusercontent.com/58435416/81208488-f8731200-8f83-11ea-938e-c2b673d35d87.JPG)

**Comment by rjcrter11** [comment]
It's giving the same error when you hit clear filters in the search page too

**Comment by rjcrter11** [comment]
Fixed it. There was a missing dependency in a useEffect in that component
