### ISSUE TITLE
destructuring react-hook-form imports breaks our app

### ISSUE THREAD

**Issue by gelinas** [Lambda-School-Labs/community-calendar-fe#28]
Destructuring imports from other libraries works like expected

Destructuring import from `react-hook-form` causes an error when rendering our application

`import {useForm} from 'react-hook-form'` works as expected in other create-react-app repos

`import {useForm} from 'react-hook-form'` does not work as expected in our application, causes errors when rendering

`import useForm from 'react-hook-form'` works fine in our application (don't destructure)

Destructuring of other hooks works fine in our application:

`import {useQuery} from 'react-apollo'` works as expected in our application

Analysis: We have no clue why just destructuring from react-hook-form causes errors rendering our application.

Thoughts on causes of bug:

React version? Custom webpack scripts? Node/NPM version?

**Comment by WStrellis** [comment]
Resolved in #29 . We had an old version of React-Hook-Form.
